USE dummyDB;

DROP TABLE IF EXISTS user_table;


CREATE TABLE IF NOT EXISTS user_table(
    user_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(64) NOT NULL, 
    password VARCHAR(256) NOT NULL,
    user_info VARCHAR(64000),
	 created DATETIME DEFAULT CURRENT_TIMESTAMP,
	 updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	 stripe_token VARCHAR(512)
	 
);
